# Fundamental Data Structures and Algorithms 04a - Arrays and Linked List - Exercise
---

The following problems should help you get familiar with the arrays and linked lists

### Question 1  
  
**(a)** When you add 2 lists together: `[1, 2, 3] + [4, 5, 6]`, you will get `[1, 2, 3, 4, 5, 6]`. However, we want to sum elements together i.e. `[1, 2, 3] + [4, 5, 6]` will return `[5, 7, 9]`. Write a function `listSum` that takes 2 lists, `listA` and `listB` as input and returns a new list with the elements added together. Assume that both lists are of the same length and only consist of numbers.

In [1]:
'''Method 1: list comprehension'''
def listSum(listA, listB):
    listSum = []
    for i in range(len(listA)):
        listSum.append(listA[i] + listB[i])
    return listSum

print(listSum([1,2,3],[4,5,6]))
print(listSum([1,3,5],[2,4,6]))

[5, 7, 9]
[3, 7, 11]


In [2]:
'''Method 2: list comprehension'''
def listSum2(listA, listB):
    return [listA[i]+listB[i] for i in range(len(listA))]

print(listSum2([1,2,3],[4,5,6]))
print(listSum2([1,3,5],[2,4,6]))

[5, 7, 9]
[3, 7, 11]


In [3]:
'''Method 3: NumPy library'''
import numpy as np
def listSum3(listA, listB):
    return np.array(listA)+np.array(listB)

print(listSum3([1,2,3],[4,5,6]))
print(listSum3([1,3,5],[2,4,6]))

[5 7 9]
[ 3  7 11]


**(b)** Write a <u>recursive</u> function `allOnes` that takes in a list `l` and an input size `n`, and returns a list consisting of $n$ ones. E.g. if $n = 3$, the function will return `[1, 1, 1]`. 

In [4]:
def allOnes(l, n):

    if n == 0:
        return l
    while n > 0:
        l.append(1)
        return allOnes(l,n-1)
        
print(allOnes([],0))
print(allOnes([],1))
print(allOnes([],2))
print(allOnes([],3))
print(allOnes([],4))

[]
[1]
[1, 1]
[1, 1, 1]
[1, 1, 1, 1]


---

### Question 2  

In mathematics, an $m \times n$ matrix is a rectangular grid of numberical values arranged in $m$ rows and $n$ columns. You will implement some of the common operations performed on matrices. For the following problems, you are to use lists to represent the matrix. You are also encouraged to write your own test cases for the functions that you have implemented.
  
For example,  
  
the row matrix, 
$\quad
a=
\begin{bmatrix}
0&1&2\\
\end{bmatrix}
\quad
$
, can be written as `a = [0, 1, 2]`,  
  
the column matrix, 
$\quad
b=
\begin{bmatrix}
3 \\
4 \\
5 \\
\end{bmatrix}
\quad
$
, can be written as `b = [[3], [4], [5]]` and,  
  
the $3 \times 2$ matrix,
$\quad
m=
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
\quad
$
, can be written as the nested list, `m = [[0, 1], [2, 3], [4, 5]]`.

**(a) Size of Matrix**  
Implement the function `getSize` that takes in a matrix `m` as input and returns the size of the matrix as a tuple in the following format $(row, column)$. This will serve as an auxilary function to the other functions that requires their matrix inputs to be of the correct sizes.

In [5]:
def getSize(m):

    row = col = len(m)
    try:
        col = len(m[0])
    except:
        row = 1
    return (row,col)


In [6]:
# Test cases
a1 = [1, 2, 3]
a2 = [[1], [2], [3]]
a3 = [[1,2], [2,3], [3,4]]
print(getSize(a1))    # expected output: (1,3)
print(getSize(a2))    # expected output: (3,1)
print(getSize(a3))    # expected output: (3,2)

(1, 3)
(3, 1)
(3, 2)


**(b) Additional and Subtraction**  
Two $m \times n$ matrices can be added or subtracted to create a third $m \times n$ matrix. When adding two $m \times n$ matrices, corresponding elements are summed as illustrated below.  
  
$$
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
+
\begin{bmatrix}
6&7 \\
8&9 \\
1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
(0+6)&(1+7) \\
(2+8)&(3+9) \\
(4+1)&(5+0) \\
\end{bmatrix}
=
\begin{bmatrix}
6&8 \\
10&12 \\
5&5 \\
\end{bmatrix}\\
$$  
  
Subtraction is performed in a similar fashion but the corresponding elements are subtracted instead of summed.
  
You are to implement the matrix addition function `matrixSum` that takes in two matrices, `mA` and `mB`, as inputs and returns the summed matrix as output. Your function should ensure that both matrices have the same size.

In [7]:
'''Method 1: create a new list and append the sum of each element'''
def matrixSum(mA, mB):

    if getSize(mA) != getSize(mB):
        return "matrices not same size"
    
    row, col = getSize(mA)
    if row == 1:
        return listSum(mA, mB)
    
    sum = []
    for i in range (len(mA)):
        sum.append([])
        for j in range(len(mA[0])):
            sum[i].append(mA[i][j]+mB[i][j])
    return sum

In [8]:
'''Method 2: list comprehension'''
def matrixSum2(mA, mB):
    if getSize(mA) != getSize(mB):
        return "matrices not same size"
    
    row, col = getSize(mA)
    if row == 1:
        return listSum(mA, mB)
    
    return [[(mA[i][j]+mB[i][j]) for j in range(len(mA[0]))] for i in range(len(mA))]

In [9]:
'''Method 3: numpy'''
import numpy as np
def matrixSum3(mA, mB):
    if getSize(mA) != getSize(mB):
        return "matrices not same size"
    return np.array(mA)+np.array(mB)

In [10]:
# Test case 1
b1 = [[0, 1], [2, 3], [4, 5]]
b2 = [[6, 7], [8, 9], [1, 0]]
# expected output: [[6, 8], [10, 12], [5, 5]]
print("test case 1")
print(matrixSum(b1, b2))
print(matrixSum2(b1, b2))
print(matrixSum3(b1, b2)) 

# Test case 2
b3 = [1,3,5]
b4 = [2,4,6]
# expected output: [3, 7, 11]
print("\ntest case 2")
print(matrixSum(b3, b4))
print(matrixSum2(b3, b4))
print(matrixSum3(b3, b4))

# Test case 3
b5 = [[0], [2], [4]]
b6 = [[6], [8], [1]]
# expected output: [[6], [10], [5]]
print("\ntest case 3")
print(matrixSum(b5, b6))
print(matrixSum2(b5, b6))
print(matrixSum3(b5, b6))

# Test case 4
b7 = [1]
b8 = [2]
# expected output: [3]
print("\ntest case 4")
print(matrixSum(b7, b8))
print(matrixSum2(b7, b8))
print(matrixSum3(b7, b8))

# Test case 5
b9 = [1, 2]
b10 = [3]
# expected output: "matrices not same size"
print("\ntest case 5")
print(matrixSum(b9, b10))
print(matrixSum2(b9, b10))
print(matrixSum3(b9, b10))

test case 1
[[6, 8], [10, 12], [5, 5]]
[[6, 8], [10, 12], [5, 5]]
[[ 6  8]
 [10 12]
 [ 5  5]]

test case 2
[3, 7, 11]
[3, 7, 11]
[ 3  7 11]

test case 3
[[6], [10], [5]]
[[6], [10], [5]]
[[ 6]
 [10]
 [ 5]]

test case 4
[3]
[3]
[3]

test case 5
matrices not same size
matrices not same size
matrices not same size


**(c) Scaling**  
matrix can be uniformly scaled, which modifies each element of the matrix by the same scale factor. A scale factor of less than $1$ has the effect of reducing the value of each element whereas a scale factor greater than $1$ increases the value of each element. Scaling a matrix by a scale factor of $3$ is illustrated here:  
  
$$
3
\begin{bmatrix}
6&7 \\
8&9 \\
1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
(3\times 6)&(3\times 7) \\
(3\times 8)&(3\times 9) \\
(3\times 1)&(3\times 0) \\
\end{bmatrix}
=
\begin{bmatrix}
18&21 \\
24&27 \\
3&0 \\
\end{bmatrix}\\
$$  
  
You are to implement the scale function `matrixScale` that takes in a matrix, `m`, and scale factor `sf`, as inputs and returns the scaled matrix as output.

In [11]:
'''Method 1: create a new list and append the scaled elements'''
def matrixScale(m, sf):
    
    row, col = getSize(m)
    scale = []
    if row == 1:
        for j in m:
            scale.append(sf * j)
    else:
        for row in range (len(m)):
            scale.append([])
            for col in range(len(m[0])):
                scale[row].append(sf*m[row][col])
    return scale

In [12]:
'''Method 2: list comprehension'''
def matrixScale2(m, sf):
    
    row, col = getSize(m)
    
    if row == 1:
        return [j*sf for j in m]
    else:
        return [[sf*(m[i][j]) for j in range(len(m[0]))] for i in range(len(m))]

In [13]:
'''Method 3: numpy'''
import numpy as np
def matrixScale3(m, sf):
    return np.array(m)*sf

In [14]:
# Test case 1
c1 = [[6, 7], [8, 9], [1, 0]]
sf = 3
# expected output: [[18, 21], [24, 27], [3, 0]]
print('test case 1')
print(matrixScale(c1, sf))     
print(matrixScale2(c1, sf))
print(matrixScale3(c1, sf))

# Test case 2
c2 = [[6], [8], [1]]
sf2 = 1
# expected output: [[6], [8], [1]]
print('\ntest case 2')
print(matrixScale(c2, sf2))     
print(matrixScale2(c2, sf2))
print(matrixScale3(c2, sf2))

# Test case 3
c3 = [1,2,3]
sf3 = 2
# expected output: [2,4,6]
print('\ntest case 3')
print(matrixScale(c3, sf3))     
print(matrixScale2(c3, sf3))
print(matrixScale3(c3, sf3))

# Test case 4
c4 = [[1,2],[3,4],[5,6]]
sf4 = 0
# expected output: [[0,0],[0,0],[0,0]]
print('\ntest case 4')
print(matrixScale(c4, sf4))     
print(matrixScale2(c4, sf4))
print(matrixScale3(c4, sf4))

# Test case 5
c5 = []
sf5 = 10
# expected output: []
print('\ntest case 5')
print(matrixScale(c5, sf5))     
print(matrixScale2(c5, sf5))
print(matrixScale3(c5, sf5))

test case 1
[[18, 21], [24, 27], [3, 0]]
[[18, 21], [24, 27], [3, 0]]
[[18 21]
 [24 27]
 [ 3  0]]

test case 2
[[6], [8], [1]]
[[6], [8], [1]]
[[6]
 [8]
 [1]]

test case 3
[2, 4, 6]
[2, 4, 6]
[2 4 6]

test case 4
[[0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0]]
[[0 0]
 [0 0]
 [0 0]]

test case 5
[]
[]
[]


**(d) Multiplication**  
Matrix multiplication is only defined for matrices where the number of columns in the matrix on the lefthand side is equal to the number of rows in the matrix on the righthand side. The result is a new matrix that contains the same number of rows as the matrix on the lefthand side and the same number of columns as the matrix on the righthand side. In other words, given a matrix of size $m \times n$ multiplied by a matrix of size $n \times p$, the resulting matrix is of size $m \times p$. In multiplying two matrices, each element of the new matrix is the result of summing the product of a row in the lefthand side matrix by a column in the righthand side matrix. In the example matrix multiplication illustrated here, the row and column used to compute the first entry i.e. $(0, 0)$ of the new matrix is in bold fonts.
  
$$
\begin{bmatrix}
\mathbf{0}&\mathbf{1} \\
2&3 \\
4&5 \\
\end{bmatrix}
\times
\begin{bmatrix}
\mathbf{6}&7&8 \\
\mathbf{9}&1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{(0\times 6 + 1\times 9)}&(0\times 7 + 1\times 1)&(0\times 8 + 1\times 0) \\
(2\times 6 + 3\times 9)&(2\times 7 + 3\times 1)&(2\times 8 + 3\times 0) \\
(4\times 6 + 5\times 9)&(4\times 7 + 5\times 1)&(4\times 8 + 5\times 0) \\
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{9}&1&0 \\
39&17&16 \\
69&33&32 \\
\end{bmatrix}\\
$$  
  
View matrix multiplication based on the element subscripts can help you to better understand the operation. Consider the two matrices from above and assume they are labeled $A$ and $B$, respectively.  
  
$$
A=
\begin{bmatrix}
\mathbf{A_{0,0}}&\mathbf{A_{0,1}} \\
A_{1,0}&A_{1,1} \\
A_{2,0}&A_{2,1} \\
\end{bmatrix}
\quad \quad
B=
\begin{bmatrix}
\mathbf{B_{0,0}}&B_{0,1}&B_{0,2} \\
\mathbf{B_{1,0}}&B_{1,1}&B_{1,2} \\
\end{bmatrix}\\
$$  

The computation of the individual elements resulting from multiplying $A$ and $B$ (i.e. $C = A \times B$) is performed as follows:

$$
C_{0,0} = A_{0,0} \times B_{0,0} + A_{0,1} \times B_{1,0}\\
C_{0,1} = A_{0,0} \times B_{0,1} + A_{0,1} \times B_{1,1}\\
C_{0,2} = A_{0,0} \times B_{0,2} + A_{0,1} \times B_{1,2}\\
C_{1,0} = A_{1,0} \times B_{0,0} + A_{1,1} \times B_{1,0}\\
C_{1,1} = A_{1,0} \times B_{0,1} + A_{1,1} \times B_{1,1}\\
C_{1,2} = A_{1,0} \times B_{0,2} + A_{1,1} \times B_{1,2}\\
C_{2,0} = A_{2,0} \times B_{0,0} + A_{2,1} \times B_{1,0}\\
C_{2,1} = A_{2,0} \times B_{0,1} + A_{2,1} \times B_{1,1}\\
C_{2,2} = A_{2,0} \times B_{0,2} + A_{2,1} \times B_{1,2}\\
$$  
  
resulting in  
  
$$
\\
C=
\begin{bmatrix}
(A_{0,0} \times B_{0,0} + A_{0,1} \times B_{1,0})&
(A_{0,0} \times B_{0,1} + A_{0,1} \times B_{1,1})&
(A_{0,0} \times B_{0,2} + A_{0,1} \times B_{1,2}) \\
(A_{1,0} \times B_{0,0} + A_{1,1} \times B_{1,0})&
(A_{1,0} \times B_{0,1} + A_{1,1} \times B_{1,1})&
(A_{1,0} \times B_{0,2} + A_{1,1} \times B_{1,2}) \\
(A_{2,0} \times B_{0,0} + A_{2,1} \times B_{1,0})&
(A_{2,0} \times B_{0,1} + A_{2,1} \times B_{1,1})&
(A_{2,0} \times B_{0,2} + A_{2,1} \times B_{1,2})
\end{bmatrix}\\
$$  
  
You are to implement the matrix multiplication function `matrixMultiplication` that takes in two matrices, `mA` and `mB`, as inputs and returns the multiplied matrix as output. The function must ensure that both matrices are of correct sizes before proceeding i.e. matrix `mA` of size $m \times n$ when multiplied with matrix `mB` of size $n \times p$ will retult in matrix `mC` of size $m \times p$.

In [15]:
'''Method 1: create a new list and append the product of each element'''
def matrixMultiplication(mA, mB):
    rA,cA = getSize(mA)
    rB,cB = getSize(mB)
    
    if cA != rB:
        return "matrices not correct size"
    
    product = []
    
    if rA == 1:         # if mA is row matrix
        if cB == 1:     # if output is []
            temp = 0
            for i in range(rB):
                temp = temp + mA[i] * mB[i][0]
            product.append(temp)
        else:
            for j in range(cB):
                temp = 0
                for i in range(rB):
                    temp = temp + mA[i] * mB[i][j]
                product.append(temp)                
    else:
        if cA == 1:
            for i in range(rA):
                #temp = 0
                product.append([])
                for j in range(cB):
                    temp = 0
                    temp = temp + mA[i][0] * mB[j]
                    product[i].append(temp)
        else:
            for i in range(rA):
                product.append([])
                for j in range(cB):
                    temp = 0
                    for k in range(cA):
                        temp = temp + mA[i][k] * mB[k][j]
                    product[i].append(temp)
                    

    return product

In [16]:
'''Method 2: numpy'''
import numpy as np
def matrixMultiplication2(mA, mB):
    rA, cA = getSize(mA)
    rB, cB = getSize(mB)
    if cA != rB:
        return "matrices not same size"
    mA = np.array(mA, ndmin = 2)
    mB = np.array(mB, ndmin = 2)
    return np.dot(mA,mB)

In [17]:
# Test case 1
d1 = [[0, 1], [2, 3], [4, 5]]
d2 = [[6, 7, 8], [9, 1, 0]]
#expected output: [[9, 1, 0], [39, 17, 16], [69, 33, 32]]
print('test case 1')
print(matrixMultiplication(d1, d2))
print(matrixMultiplication2(d1, d2))

# Test case 2
d3 = [1, 2, 3]
d4 = [[2],[3],[4]]
#expected output: [20]
print('\ntest case 2')
print(matrixMultiplication(d3, d4))
print(matrixMultiplication2(d3, d4))

# Test case 3
d5 = [1, 2, 3]
d6 = [[2,1,0],[3,2,1],[4,3,2]]
#expected output: [[20],[14]]
print('\ntest case 3')
print(matrixMultiplication(d5, d6))
print(matrixMultiplication2(d5, d6))

# Test case 4
d7 = [[1],[2],[3]]
d8 = [4,5,6]
#expected output: [[20],[14]]
print('\ntest case 4')
print(matrixMultiplication(d7, d8))
print(matrixMultiplication2(d7, d8))

test case 1
[[9, 1, 0], [39, 17, 16], [69, 33, 32]]
[[ 9  1  0]
 [39 17 16]
 [69 33 32]]

test case 2
[20]
[[20]]

test case 3
[20, 14, 8]
[[20 14  8]]

test case 4
[[4, 5, 6], [8, 10, 12], [12, 15, 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**(e) Transpose**  
Another useful operation that can be applied to a matrix is the matrix transpose. Given a $m \times n$ matrix, a transpose swaps the rows and columns to create a new matrix of size $n \times m$ as illustrated here:  
  
$$
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
^{\ T}
=
\begin{bmatrix}
0&2&4 \\
1&3&5 \\
\end{bmatrix}\\
$$  
  
You are to implement the matrix transpose function `matrixTranspose` that takes in a matrix, `m`,  and returns the transposed matrix as output.

In [18]:
'''Method 1: fatten 2d to 1d before populating'''
def matrixTranspose(m):    
    r, c = getSize(m)
    if r==1:
        if c==1:
            return m
        else:
            return [[m[x]] for x in range(c)]
    else:
        temp = sum(m, [])
        t = []
        if r==1:
            return [m[y][0] for y in range(r)]
        else:
            for i in range(c):
                t.append([])
                for j in range(r):
                    t[i].append(temp[i+j*c])
    return t

In [19]:
'''Method 2: numpy'''
def matrixTranspose2(m):
    m = np.array(m, ndmin = 2)
    return np.transpose(m)

In [20]:
# Test cases 1
e1 = [[0, 1], [2, 3], [4, 5]]
# expected output: [[0, 2, 4], [1, 3, 5]]
print('test case 1')
print(matrixTranspose(e1))
print(matrixTranspose2(e1))

# Test case 2
e2 = [[0, 1, 2], [2, 3, 4], [4, 5, 6]]
# expected output: [[0, 2, 4], [1, 3, 5]]
print('\ntest case 2')
print(matrixTranspose(e2))
print(matrixTranspose2(e2))

# Test case 3
e3 = [0, 1, 2]
# expected output: [[0], [1], [2]]
print('\ntest case 3')
print(matrixTranspose(e3))
print(matrixTranspose2(e3))

# Test case 4
e4 = [[0], [1], [2]]
# expected output: [[0, 1, 2]]
print('\ntest case 4')
print(matrixTranspose(e4))
print(matrixTranspose2(e4))

test case 1
[[0, 2, 4], [1, 3, 5]]
[[0 2 4]
 [1 3 5]]

test case 2
[[0, 2, 4], [1, 3, 5], [2, 4, 6]]
[[0 2 4]
 [1 3 5]
 [2 4 6]]

test case 3
[[0], [1], [2]]
[[0]
 [1]
 [2]]

test case 4
[[0, 1, 2]]
[[0 1 2]]


**(f) NumPy Array**  
  
NumPy is a popular Python library that supports many mathematical functions. Instead of using *lists* to represent a matrix, a NumPy array is much more suitable.  
  
Similarly,  
  
the row matrix, 
$\quad
a=
\begin{bmatrix}
0&1&2\\
\end{bmatrix}
\quad
$
, can be written as `a = np.array([0, 1, 2])`,  
  
the column matrix, 
$\quad
b=
\begin{bmatrix}
3 \\
4 \\
5 \\
\end{bmatrix}
\quad
$
, can be written as `b = np.array([[3], [4], [5]])` and,  
  
the $3 \times 2$ matrix,
$\quad
m=
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
\quad
$
, can be written as the nested list, `m = np.array([[0, 1], [2, 3], [4, 5]])`.  
  
For each of the matrix operations above, you are to find their equivalent functions within the NumPy module. You are to compare your results

In [21]:
#refer to above

---

### Question 3  
  
**(a)**  In the linked list presented in the notes, each node maintains a reference to the node that is immediately after it. A **doubly linked list** is a linked list that references <u>both the node before and after it</u>. This provides a greater flexibility as compared to the standard linked list.

![doubly linked list](https://i.ibb.co/ftMwyZt/Slide49.png)

Complete the implementation of the doubly linked list class below. The class `Node` and the ` __init__()` method have been done for you.

In [46]:
class DoublyLinkedList:
    
    class Node:
        def __init__(self, data, prev, next):
            self.data = data
            self.prev = prev
            self.next = next
            
    def __init__(self):
        self.head = self.Node(None, None, None)
        self.tail = self.Node(None, None, None)
        self.head.next = self.tail
        self.tail.prev = self.head
        self.size = 0
        
    # this will return the number of nodes in your linked list (aka length of the list)
    def __len__(self):
        # Implement your code here
        return self.size
    
    # this will return a True if list is empty
    def isEmpty(self):
        # Implement your code here
        return self.size == 0
    
    # this will insert a node between two existing nodes and return new node
    def insert(self, newData, predecessor, successor):
        # Implement your code here
        newNode = self.Node(newData, predecessor, successor)
        predecessor.next = newNode
        successor.prev = newNode
        self.size += 1
        return newNode
        
    # deletes node and returns the deleted data, returns None if no such node exists
    def deleteNode(self,node):
        # Implement your code here
        predecessor = node.prev
        successor = node.next
        predecessor.next = successor
        successor.prev = predecessor
        self.size -= 1
        deletedData = node.data
        node.prev = node.next = node.data = None
        return deletedData
        
    
    # prints list data from head to tail or prints "list is empty" if list is empty
    def forwardPrint(self):
        # Implement your code here
        if self.isEmpty():
            return "list is empty"
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
    
    # prints list data from tail back to head or prints "list is empty" if list is empty
    def reversePrint(self):
        # Implement your code here
        if self.isEmpty():
            return "list is empty"
        temp = self.tail
        while(temp):
            print(temp.data)
            temp = temp.prev
    

**(b)** You are to implement your own test cases to ensure that your doubly linked list class is implemented correctly.

In [47]:
# Do not modify this cell.
# Run this before running the test cases below.
dll = DoublyLinkedList()

In [48]:
# Test 1: verify that the list is empty; expected output: True
# Implement your code here
dll.isEmpty()

True

In [49]:
# Test 2: check the length of the list; expected output: 0
# Implement your code here
len(dll)

0

In [50]:
# Test 3: print list; expected output: "list is empty"
# Implement your code here
dll.forwardPrint()

'list is empty'

In [51]:
# Test 4: Insert '2'
# Implement your code here
dll.insert(2, dll.head, dll.tail)

In [52]:
# Test 5: Insert '3' at tail
# Implement your code here
dll.insert(3, dll.tail.prev, dll.tail)

In [53]:
# Test 6: Insert '1' at head
# Implement your code here
dll.insert(1, dll.head, dll.head.next)

In [54]:
# Test 7: check if list is empty; expected output: False
# Implement your code here
dll.isEmpty()

False

In [55]:
# Test 8: verify the length of the list; expected output: 3
# Implement your code here
len(dll)

3

In [56]:
# Test 9: print list forwards; expected output: 1 2 3
# Implement your code here
dll.forwardPrint()

None
1
2
3
None


In [57]:
# Test 10: Delete '2'
# Implement your code here
dll.deleteNode(dll.head.next.next)

2

In [58]:
# Test 11: verify the length of the list; expected output: 2
# Implement your code here
len(dll)

2

In [59]:
# Test 12: print list in reverse; expected output: 3 1
# Implement your code here
dll.reversePrint()

None
3
1
None


In [60]:
# Test 13: Delete '1'
# Implement your code here
dll.deleteNode(dll.head.next)

1

In [61]:
# Test 14: Delete '3'
# Implement your code here
dll.deleteNode(dll.head.next)

3

In [62]:
# Test 15: Delete '4', expected output: Error
# Implement your code here
dll.deleteNode(dll.head.next)

AttributeError: 'NoneType' object has no attribute 'prev'

In [66]:
# Test 16: Repeat Tests #1, #2, #3. You can copy code here.
# Implement your code here
print(dll.isEmpty(), len(dll), dll.forwardPrint(), sep = '\n')

True
0
list is empty


**(c)** Write a function `listToDLL` that takes a list and returns a doubly linked list.

In [71]:
def listToDLL(listDLL):
    # implement your code here
    dll = DoublyLinkedList()
    while listDLL!=[]:
        dll.insert(listDLL.pop(), dll.head, dll.head.next)
    return dll

In [72]:
# Run this cell to test your code
myList = [1, 2, 3]
dll2 = listToDLL(myList) 
dll2.forwardPrint() # expected output: 1 2 3; dll2 can also be tested with the test cases in (b)

None
1
2
3
None
