# Fundamental Data Structures and Algorithms 04a - Arrays and Linked List - Exercise
---

The following problems should help you get familiar with the arrays and linked lists

### Question 1  
  
**(a)** When you add 2 lists together: `[1, 2, 3] + [4, 5, 6]`, you will get `[1, 2, 3, 4, 5, 6]`. However, we want to sum elements together i.e. `[1, 2, 3] + [4, 5, 6]` will return `[5, 7, 9]`. Write a function `listSum` that takes 2 lists, `listA` and `listB` as input and returns a new list with the elements added together. Assume that both lists are of the same length and only consist of numbers.

In [1]:
def listSum(listA, listB):
    # write your code here
    new_lst = []
    for i in range(len(listA)):
        new_lst.append(listA[i] + listB[i])
    return new_lst


In [7]:
def listSum(listA, listB):
    return list(map((lambda x,y:x+y), listA, listB))

In [19]:
import numpy as np

def listSum(listA, listB):
    A = np.array(listA)
    B = np.array(listB)
    return list(A+B)

In [20]:
###### Test code #########
listA = [1, 2, 3]
listB = [4, 5, 6]

listSum(listA, listB)

[5, 7, 9]

**(b)** Write a <u>recursive</u> function `allOnes` that takes in a list `l` and an input size `n`, and returns a list consisting of $n$ ones. E.g. if $n = 3$, the function will return `[1, 1, 1]`. 

In [35]:
def allOnes(l, n):
    # write your code here
    if n == 0:
        return l
    else:
        l.append(1)
        return allOnes(l, n-1)

In [37]:
allOnes([], 5)

[1, 1, 1, 1, 1]

---

### Question 2  

In mathematics, an $m \times n$ matrix is a rectangular grid of numberical values arranged in $m$ rows and $n$ columns. You will implement some of the common operations performed on matrices. For the following problems, you are to use lists to represent the matrix. You are also encouraged to write your own test cases for the functions that you have implemented.
  
For example,  
  
the row matrix, 
$\quad
a=
\begin{bmatrix}
0&1&2\\
\end{bmatrix}
\quad
$
, can be written as `a = [0, 1, 2]`,  
  
the column matrix, 
$\quad
b=
\begin{bmatrix}
3 \\
4 \\
5 \\
\end{bmatrix}
\quad
$
, can be written as `b = [[3], [4], [5]]` and,  
  
the $3 \times 2$ matrix,
$\quad
m=
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
\quad
$
, can be written as the nested list, `m = [[0, 1], [2, 3], [4, 5]]`.

**(a) Size of Matrix**  
Implement the function `getSize` that takes in a matrix `m` as input and returns the size of the matrix as a tuple in the following format $(row, column)$. This will serve as an auxilary function to the other functions that requires their matrix inputs to be of the correct sizes.

In [33]:
def getSize(m):
    # implement your code here
    if isinstance(m[0], list):
        return len(m), len(m[0])
    else:
        return 1, len(m)
        

In [34]:
# Test cases
a1 = [1, 2, 3]
a2 = [[1], [2], [3]]
print(getSize(a1))    # expected output: (1,3)
print(getSize(a2))    # expected output: (3,1)
# Write your test cases here


(1, 3)
(3, 1)


**(b) Additional and Subtraction**  
Two $m \times n$ matrices can be added or subtracted to create a third $m \times n$ matrix. When adding two $m \times n$ matrices, corresponding elements are summed as illustrated below.  
  
$$
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
+
\begin{bmatrix}
6&7 \\
8&9 \\
1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
(0+6)&(1+7) \\
(2+8)&(3+9) \\
(4+1)&(5+0) \\
\end{bmatrix}
=
\begin{bmatrix}
6&8 \\
10&12 \\
5&5 \\
\end{bmatrix}\\
$$  
  
Subtraction is performed in a similar fashion but the corresponding elements are subtracted instead of summed.
  
You are to implement the matrix addition function `matrixSum` that takes in two matrices, `mA` and `mB`, as inputs and returns the summed matrix as output. Your function should ensure that both matrices have the same size.

In [44]:
def matrixSum(mA, mB):
    # implement your code here
    r, c = getSize(mA)
    result = mA.copy()
    for i in range(r):
        for j in range(c):
            result[i][j] += mB[i][j]
    return result

In [45]:
# Test cases
b1 = [[0, 1], [2, 3], [4, 5]]
b2 = [[6, 7], [8, 9], [1, 0]]
b3 = matrixSum(b1, b2)    # expected output: [[6, 8], [10, 12], [5, 5]]
print(b3)
# Write your test cases here


[[6, 8], [10, 12], [5, 5]]


**(c) Scaling**  
matrix can be uniformly scaled, which modifies each element of the matrix by the same scale factor. A scale factor of less than $1$ has the effect of reducing the value of each element whereas a scale factor greater than $1$ increases the value of each element. Scaling a matrix by a scale factor of $3$ is illustrated here:  
  
$$
3
\begin{bmatrix}
6&7 \\
8&9 \\
1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
(3\times 6)&(3\times 7) \\
(3\times 8)&(3\times 9) \\
(3\times 1)&(3\times 0) \\
\end{bmatrix}
=
\begin{bmatrix}
18&21 \\
24&27 \\
3&0 \\
\end{bmatrix}\\
$$  
  
You are to implement the scale function `matrixScale` that takes in a matrix, `m`, and scale factor `sf`, as inputs and returns the scaled matrix as output.

In [46]:
def matrixScale(m, sf):
    # implement your code here
    r, c = getSize(m)
    result = m.copy()
    for i in range(r):
        for j in range(c):
            result[i][j] *= sf
    return result

In [47]:
# Test cases
c1 = [[6, 7], [8, 9], [1, 0]]
c2 = matrixScale(c1, 3)
print(c2)    # expected output: [[18, 21], [24, 27], [3, 0]]
# Write your test cases here


[[18, 21], [24, 27], [3, 0]]


**(d) Multiplication**  
Matrix multiplication is only defined for matrices where the number of columns in the matrix on the lefthand side is equal to the number of rows in the matrix on the righthand side. The result is a new matrix that contains the same number of rows as the matrix on the lefthand side and the same number of columns as the matrix on the righthand side. In other words, given a matrix of size $m \times n$ multiplied by a matrix of size $n \times p$, the resulting matrix is of size $m \times p$. In multiplying two matrices, each element of the new matrix is the result of summing the product of a row in the lefthand side matrix by a column in the righthand side matrix. In the example matrix multiplication illustrated here, the row and column used to compute the first entry i.e. $(0, 0)$ of the new matrix is in bold fonts.
  
$$
\begin{bmatrix}
\mathbf{0}&\mathbf{1} \\
2&3 \\
4&5 \\
\end{bmatrix}
\times
\begin{bmatrix}
\mathbf{6}&7&8 \\
\mathbf{9}&1&0 \\
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{(0\times 6 + 1\times 9)}&(0\times 7 + 1\times 1)&(0\times 8 + 1\times 0) \\
(2\times 6 + 3\times 9)&(2\times 7 + 3\times 1)&(2\times 8 + 3\times 0) \\
(4\times 6 + 5\times 9)&(4\times 7 + 5\times 1)&(4\times 8 + 5\times 0) \\
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{9}&1&0 \\
39&17&16 \\
69&33&32 \\
\end{bmatrix}\\
$$  
  
View matrix multiplication based on the element subscripts can help you to better understand the operation. Consider the two matrices from above and assume they are labeled $A$ and $B$, respectively.  
  
$$
A=
\begin{bmatrix}
\mathbf{A_{0,0}}&\mathbf{A_{0,1}} \\
A_{1,0}&A_{1,1} \\
A_{2,0}&A_{2,1} \\
\end{bmatrix}
\quad \quad
B=
\begin{bmatrix}
\mathbf{B_{0,0}}&B_{0,1}&B_{0,2} \\
\mathbf{B_{1,0}}&B_{1,1}&B_{1,2} \\
\end{bmatrix}\\
$$  

The computation of the individual elements resulting from multiplying $A$ and $B$ (i.e. $C = A \times B$) is performed as follows:

$$
C_{0,0} = A_{0,0} \times B_{0,0} + A_{0,1} \times B_{1,0}\\
C_{0,1} = A_{0,0} \times B_{0,1} + A_{0,1} \times B_{1,1}\\
C_{0,2} = A_{0,0} \times B_{0,2} + A_{0,1} \times B_{1,2}\\
C_{1,0} = A_{1,0} \times B_{0,0} + A_{1,1} \times B_{1,0}\\
C_{1,1} = A_{1,0} \times B_{0,1} + A_{1,1} \times B_{1,1}\\
C_{1,2} = A_{1,0} \times B_{0,2} + A_{1,1} \times B_{1,2}\\
C_{2,0} = A_{2,0} \times B_{0,0} + A_{2,1} \times B_{1,0}\\
C_{2,1} = A_{2,0} \times B_{0,1} + A_{2,1} \times B_{1,1}\\
C_{2,2} = A_{2,0} \times B_{0,2} + A_{2,1} \times B_{1,2}\\
$$  
  
resulting in  
  
$$
\\
C=
\begin{bmatrix}
(A_{0,0} \times B_{0,0} + A_{0,1} \times B_{1,0})&
(A_{0,0} \times B_{0,1} + A_{0,1} \times B_{1,1})&
(A_{0,0} \times B_{0,2} + A_{0,1} \times B_{1,2}) \\
(A_{1,0} \times B_{0,0} + A_{1,1} \times B_{1,0})&
(A_{1,0} \times B_{0,1} + A_{1,1} \times B_{1,1})&
(A_{1,0} \times B_{0,2} + A_{1,1} \times B_{1,2}) \\
(A_{2,0} \times B_{0,0} + A_{2,1} \times B_{1,0})&
(A_{2,0} \times B_{0,1} + A_{2,1} \times B_{1,1})&
(A_{2,0} \times B_{0,2} + A_{2,1} \times B_{1,2})
\end{bmatrix}\\
$$  
  
You are to implement the matrix multiplication function `matrixMultiplication` that takes in two matrices, `mA` and `mB`, as inputs and returns the multiplied matrix as output. The function must ensure that both matrices are of correct sizes before proceeding i.e. matrix `mA` of size $m \times n$ when multiplied with matrix `mB` of size $n \times p$ will retult in matrix `mC` of size $m \times p$

In [52]:
def matrixMultiplication(mA, mB):
    # Write your implementation here
    ra, ca = getSize(mA)
    rb, cb = getSize(mB)
    result = []
    if ca == rb:
        for m in range(ra):
            result.append([])
            for p in range(cb):
                result[m].append(0)
                for n in range(ca):
                    result[m][p] += mA[m][n] * mB[n][p]
        return result
    else:
        assert("shape error")

In [53]:
# Test cases
d1 = [[0, 1], [2, 3], [4, 5]]
d2 = [[6, 7, 8], [9, 1, 0]]
d3 = matrixMultiplication(d1, d2)
print(d3)    # expected output: [[9, 1, 0], [39, 17, 16], [69, 33, 32]]
# Write your test cases here


[[9, 1, 0], [39, 17, 16], [69, 33, 32]]


**(e) Transpose**  
Another useful operation that can be applied to a matrix is the matrix transpose. Given a $m \times n$ matrix, a transpose swaps the rows and columns to create a new matrix of size $n \times m$ as illustrated here:  
  
$$
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
^{\ T}
=
\begin{bmatrix}
0&2&4 \\
1&3&5 \\
\end{bmatrix}\\
$$  
  
You are to implement the matrix transpose function `matrixTranspose` that takes in a matrix, `m`,  and returns the transposed matrix as output.

In [61]:
def matrixTranspose(m):
    # Write your implementation here
    r, c = getSize(m)
    result = []
    for j in range(c):
        result.append([])
        
    for i in range(r):
        for j in range(c):
            result[j].append(m[i][j])
    return result

In [62]:
# Test cases
e1 = [[0, 1], [2, 3], [4, 5]]
e2 = matrixTranspose(e1)
print(e2)    # expected output: [[0, 2, 4], [1, 3, 5]]
# Write your test cases here


[[0, 2, 4], [1, 3, 5]]


**(f) NumPy Array**  
  
NumPy is a popular Python library that supports many mathematical functions. Instead of using *lists* to represent a matrix, a NumPy array is much more suitable.  
  
Similarly,  
  
the row matrix, 
$\quad
a=
\begin{bmatrix}
0&1&2\\
\end{bmatrix}
\quad
$
, can be written as `a = np.array([0, 1, 2])`,  
  
the column matrix, 
$\quad
b=
\begin{bmatrix}
3 \\
4 \\
5 \\
\end{bmatrix}
\quad
$
, can be written as `b = np.array([[3], [4], [5]])` and,  
  
the $3 \times 2$ matrix,
$\quad
m=
\begin{bmatrix}
0&1 \\
2&3 \\
4&5 \\
\end{bmatrix}
\quad
$
, can be written as the nested list, `m = np.array([[0, 1], [2, 3], [4, 5]])`.  
  
For each of the matrix operations above, you are to find their equivalent functions within the NumPy module. You are to compare your results

In [72]:
import numpy as np

# Write your code here
print(np.array(listA) + np.array(listB))
print(np.ones((1, 5)))
print(np.array(a1).shape)
print(np.array(a2).shape)
print(np.array(c1) * 3)
print(np.dot(np.array(d1), np.array(d2)))
print(np.array(e1).T)

[5 7 9]
[[1. 1. 1. 1. 1.]]
(3,)
(3, 1)
[[54 63]
 [72 81]
 [ 9  0]]
[[ 9  1  0]
 [39 17 16]
 [69 33 32]]
[[0 2 4]
 [1 3 5]]


---

### Question 3  
  
**(a)**  In the linked list presented in the notes, each node maintains a reference to the node that is immediately after it. A **doubly linked list** is a linked list that references <u>both the node before and after it</u>. This provides a greater flexibility as compared to the standard linked list.

![doubly linked list](https://i.ibb.co/ftMwyZt/Slide49.png)

Complete the implementation of the doubly linked list class below. The class `Node` and the ` __init__()` method have been done for you.

In [1]:
class DoublyLinkedList:
    
    class Node:
        def __init__(self, data, prev, next):
            self.data = data
            self.prev = prev
            self.next = next
            
    def __init__(self):
        self.head = self.Node(None, None, None)
        self.tail = self.Node(None, None, None)
        self.head.next = self.tail
        self.tail.prev = self.head
        self.size = 0
        
    # this will return the number of nodes in your linked list (aka length of the list)
    def __len__(self):
        # Implement your code here
        # return self.size    #### this one have bug if add same node twice
        if self.head.next == self.tail:
            self.size = 0
            return self.size
        self.size = 0
        current_node = self.head
        while True:
            current_node = current_node.next
            if current_node == self.tail:
                break
            self.size += 1
        return self.size    
        
    # this will return a True if list is empty
    def isEmpty(self):
        # Implement your code here
        return self.__len__() == 0
    
    # this will insert a node between two existing nodes and return new node
    def insert(self, newData, predecessor, successor):
        # Implement your code here
        newNode = self.Node(newData, predecessor, successor)
        predecessor.next = newNode
        successor.prev = newNode
        #self.size += 1
        return newNode
    
    # deletes node and returns the deleted data, returns None if no such node exists
    def deleteNode(self,node):
        # Implement your code here
        if node.prev == None and node.next == None:
            return None
        
        node.prev.next = node.next
        node.next.prev = node.prev
        #self.size -= 1
        return node.data 
        
    # prints list data from head to tail or prints "list is empty" if list is empty
    def forwardPrint(self):
        # Implement your code here
        if self.__len__() == 0:
            print("list is empty")
        else:
            node_to_be_printed = self.head
            while True:
                node_to_be_printed = node_to_be_printed.next
                if node_to_be_printed == self.tail:
                    #print(self.tail.data)
                    break
                else:
                    print(node_to_be_printed.data)
                    
                
    
    # prints list data from tail back to head or prints "list is empty" if list is empty
    def reversePrint(self):
        # Implement your code here
        if self.__len__() == 0:
            print("list is empty")
        else:
            node_to_be_printed = self.tail
            while True:
                node_to_be_printed = node_to_be_printed.prev
                if node_to_be_printed == self.head:
                    #print(self.head.data)
                    break
                else:
                    print(node_to_be_printed.data)
                    

**(b)** You are to implement your own test cases to ensure that your doubly linked list class is implemented correctly.

In [151]:
# Do not modify this cell.
# Run this before running the test cases below.
dll = DoublyLinkedList()

In [152]:
# Test 1: verify that the list is empty; expected output: True
# Implement your code here
dll.isEmpty()

True

In [153]:
# Test 2: check the length of the list; expected output: 0
# Implement your code here
dll.__len__()

0

In [154]:
# Test 3: print list; expected output: "list is empty"
# Implement your code here
dll.forwardPrint()

list is empty


In [155]:
# Test 4: Insert '2'
# Implement your code here
node2 = dll.insert('2', dll.head, dll.tail)

In [156]:
# Test 5: Insert '3' at tail
# Implement your code here
node3 = dll.insert('3', node2, dll.tail)

In [157]:
# Test 6: Insert '1' at head
# Implement your code here
node1 = dll.insert('1', dll.head, node2)

In [158]:
# Test 7: check if list is empty; expected output: False
# Implement your code here
dll.isEmpty()

False

In [159]:
# Test 8: verify the length of the list; expected output: 3
# Implement your code here
dll.__len__()

3

In [160]:
# Test 9: print list forwards; expected output: 1 2 3
# Implement your code here
dll.forwardPrint()

1
2
3


In [161]:
# Test 10: Delete '2'
# Implement your code here
dll.deleteNode(node2)

'2'

In [163]:
# Test 11: verify the length of the list; expected output: 2
# Implement your code here
dll.__len__()

2

In [164]:
# Test 12: print list in reverse; expected output: 3 1
# Implement your code here
dll.reversePrint()

3
1


In [165]:
# Test 13: Delete '1'
# Implement your code here
dll.deleteNode(node1)

'1'

In [166]:
# Test 14: Delete '3'
# Implement your code here
dll.deleteNode(node3)

'3'

In [171]:
# Test 15: Delete '4', expected output: None
# Implement your code here
node4 = dll.Node('4', None, None)
print(dll.deleteNode(node4))

None


In [172]:
# Test 16: Repeat Tests #1, #2, #3. You can copy code here.
# Implement your code here
print(dll.isEmpty())
print(dll.__len__())
dll.forwardPrint()

True
0
list is empty


**(c)** Write a function `listToDLL` that takes a list and returns a doubly linked list.

In [173]:
# implement your code here
def listToDLL(lst):
    dll = DoublyLinkedList()
    for data in lst:
        next_node = dll.tail
        prev_node = dll.tail.prev
        dll.insert(data, prev_node, next_node)
    return dll

In [176]:
# Test your code here
lst = ['5', '4', '3']
dll = listToDLL(lst)
dll.forwardPrint()
print()
dll.reversePrint()

5
4
3

3
4
5
