In [2]:
import numpy as np

# Question 5

In [7]:
#define first matrix
A = np.array([
    [7,-2,-2],
    [4,-9,10],
    [9,2,8]
])
print(A)
#define second matrix
B = np.array([
    [7,9,3],
    [7,-7,-9],
    [1,6,5]
])
print(B)

[[ 7 -2 -2]
 [ 4 -9 10]
 [ 9  2  8]]
[[ 7  9  3]
 [ 7 -7 -9]
 [ 1  6  5]]


In [6]:
# Hadamard Product
C = A * B
print(C)

[[ 49 -18  -6]
 [ 28  63 -90]
 [  9  12  40]]


In [8]:
# Dot Product
C = A.dot(B)
print(C)

[[ 33  65  29]
 [-25 159 143]
 [ 85 115  49]]


In [ ]:
#define first matrix
A = np.array([
    [7,-2,-2],
    [4,-9,10],
    [9,2,8]
])
print(A)
#define second matrix
B = np.array([
    [7,9,3],
    [7,-7,-9],
    [1,6,5]
])
print(B)

In [ ]:
from numpy.linalg import solve
X2 = solve(A,B)
print(X2)

# Question 6

In [9]:
#define first matrix
A = np.array([
    [1,1,1,1,1],
    [1,2,3,4,5],
    [1,3,6,10,15],
    [1,4,10,20,35],
    [1,5,15,35,70]
])
print(A)

[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 1  3  6 10 15]
 [ 1  4 10 20 35]
 [ 1  5 15 35 70]]


In [11]:
from numpy.linalg import det
print(det(A))

0.9999999999999998


# Question 3

In [12]:
A = np.array([
    [1,2],
    [2,4],
    [3,6]
])

In [20]:
B = A.dot(A.T)
print(A.dot(A.T))

[[ 5 10 15]
 [10 20 30]
 [15 30 45]]


In [17]:
C = A.T.dot(A)
print(A.T.dot(A))

[[14 28]
 [28 56]]


In [18]:
from numpy.linalg import eig
values, vectors = eig(C)
print(values)
print(vectors)

[ 0. 70.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [21]:
from numpy.linalg import eig
values, vectors = eig(B)
print(values)
print(vectors)

[7.00000000e+01 3.42348056e-15 7.86710410e-31]
[[-2.67261242e-01 -8.99989016e-01 -2.59226735e-16]
 [-5.34522484e-01 -1.58890294e-01 -8.32050294e-01]
 [-8.01783726e-01  4.05923201e-01  5.54700196e-01]]


# Question 4

In [23]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
    [1,1,0],
    [1,0,1],
    [0,1,1]])
print(A)
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 1 0]
 [1 0 1]
 [0 1 1]]
[[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [-0.          0.81649658  0.57735027]]
[[-1.41421356 -0.70710678 -0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]
[[ 1.00000000e+00  1.00000000e+00 -3.09999437e-16]
 [ 1.00000000e+00 -1.11022302e-16  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.00000000e+00]]


In [24]:
print(Q.T)

[[-0.70710678 -0.70710678 -0.        ]
 [ 0.40824829 -0.40824829  0.81649658]
 [-0.57735027  0.57735027  0.57735027]]


In [26]:
print(Q*np.sqrt(12))

[[-2.44948974  1.41421356 -2.        ]
 [-2.44948974 -1.41421356  2.        ]
 [-0.          2.82842712  2.        ]]


In [27]:
print(R)

[[-1.41421356 -0.70710678 -0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]
